### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jenniehuang**
second PR

### CODE REVIEW

**Comment by jenniehuang** [comment]
http://13.208.55.153:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93
http://13.208.55.153:3000/api/attraction/3
http://13.208.55.153:3000/api/attractions?page=1

**Review by cwpeng — CHANGES_REQUESTED** [review]
According to API specification, response of http://13.208.55.153:3000/api/attraction/3 should be wrapped in "data" field. Fix it, commit a new version, and leave comment for me to review again.

**Comment by jenniehuang** [comment]
> According to API specification, response of http://13.208.55.153:3000/api/attraction/3 should be wrapped in "data" field. Fix it, commit a new version, and leave comment for me to review again.

fixed it! please review again.

**Review by cwpeng — APPROVED** [review]
Done. Good Job. :)

**Comment by cwpeng** [comment]
For a good work flow, before doing the next task, merge approved pull request first.

**Pull request merged**
