### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jenniehuang**
PR for week3
http://13.208.55.153:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Line height of attraction info text below, should be larger. Fix and leave comment for me to review again.

**Comment by jenniehuang** [comment]
just fixed the ine height!

**Comment by cwpeng** [comment]
ohoh, I mean line-height of these text.

未命名-2

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by jenniehuang** [comment]
This week only have done. not well done 😱

**Pull request merged**
